//Language Change

const translations = {
    en: {
        "nav.home": "Home",
        "nav.about": "About Us",
        "nav.support": "Support Our Effort",
        "nav.partner": "Become a Partner",
        "nav.volunteer": "Volunteer",
        "nav.sponsor": "Sponsor Us",
        "nav.materialSupport": "Material & Financial Support",
        "nav.atrium": "Atrium",
        "nav.photoSalon": "Photo Salon",
        "nav.videoShowcase": "Video Showcase",
        "nav.programs": "Programs/Projects",
        "nav.contact": "Contact Us",
        "vision.title": "Vision",
        "mission.title": "Mission Statement",
        "MotivatingTale.title": "Highlighting Motivating Tales",
        "footer.home": "Home",
        "footer.about": "About Us",
        "footer.support": "Support Our Effort",
        "footer.programs": "Programs/Projects",
        "footer.contact": "Contact Us",
        "project.knowMore": "Know More...",
        "engage.h2": "Engage With Us",
        "engage.volunteer": "Become a Volunteer",
        "engage.patronize": "Patronize Us",
        "engage.thoughts": "Let Us Know Your Thoughts",
        "contact.officeAddress": "Office Address",
        "contact.writeToUs": "Write to Us",
        "contact.name": "Name:",
        "contact.organization": "Organization (Optional):",
        "contact.phone": "Phone (Optional):",
        "contact.email": "E-mail (Required):",
        "contact.message": "Message (max 250 words):",
        "contact.send": "SEND",

        "bn.volunteer": "Bangladeshi Member/Volunteer",
        "volunteer.firstName": "First Name*",
        "volunteer.lastName": "Last Name*",
        "volunteer.email": "E-mail*",
        "volunteer.phone": "Phone/Cell Number*",
        "volunteer.gender": "Gender*",
        "Gender.genderSelect": "Select Gender",
        "volunteerGender.male": "Male",
        "volunteerGender.female": "Female",
        "volunteerGender.other": "Other",

        "bn.religion": "Religion (Optional)",
        "religion.select": "Select Religion",
        "religion.hinduism": "Sanatan",
        "religion.buddhism": "Buddhism",
        "religion.christianity": "Christianity",
        "religion.islam": "Islam",
        "religion.other": "Other",
        "religion.no_religion": "No Religion",

        "bn.area": "Area*",
        "area.select": "Select Area",
        "bn.bandarban": "Bandarban",
        "bn.barguna": "Barguna",
        "bn.barisal": "Barisal",
        "bn.bhola": "Bhola",
        "bn.bogura": "Bogura",
        "bn.brahmanbaria": "Brahmanbaria",
        "bn.chandpur": "Chandpur",
        "bn.chattogram": "Chattogram",
        "bn.chuadanga": "Chuadanga",
        "bn.coxsbazar": "Cox's Bazar",
        "bn.cumilla": "Cumilla",
        "bn.dhaka": "Dhaka",
        "bn.dinajpur": "Dinajpur",
        "bn.faridpur": "Faridpur",
        "bn.feni": "Feni",
        "bn.gaibandha": "Gaibandha",
        "bn.gazipur": "Gazipur",
        "bn.gopalganj": "Gopalganj",
        "bn.habiganj": "Habiganj",
        "bn.jamalpur": "Jamalpur",
        "bn.jashore": "Jashore",
        "bn.jhalkathi": "Jhalkathi",
        "bn.jhinaidah": "Jhinaidah",
        "bn.joypurhat": "Joypurhat",
        "bn.khagrachari": "Khagrachari",
        "bn.khulna": "Khulna",
        "bn.kishoreganj": "Kishoreganj",
        "bn.kurigram": "Kurigram",
        "bn.kushtia": "Kushtia",
        "bn.lakshmipur": "Lakshmipur",
        "bn.lalmonirhat": "Lalmonirhat",
        "bn.madaripur": "Madaripur",
        "bn.magura": "Magura",
        "bn.manikganj": "Manikganj",
        "bn.meherpur": "Meherpur",
        "bn.moulvibazar": "Moulvibazar",
        "bn.munshiganj": "Munshiganj",
        "bn.mymensingh": "Mymensingh",
        "bn.naogaon": "Naogaon",
        "bn.narail": "Narail",
        "bn.narayanganj": "Narayanganj",
        "bn.narsingdi": "Narsingdi",
        "bn.natore": "Natore",
        "bn.netrokona": "Netrokona",
        "bn.nilphamari": "Nilphamari",
        "bn.noakhali": "Noakhali",
        "bn.pabna": "Pabna",
        "bn.panchagarh": "Panchagarh",
        "bn.patuakhali": "Patuakhali",
        "bn.pirojpur": "Pirojpur",
        "bn.rajbari": "Rajbari",
        "bn.rajshahi": "Rajshahi",
        "bn.rangamati": "Rangamati",
        "bn.rangpur": "Rangpur",
        "bn.satkhira": "Satkhira",
        "bn.shariatpur": "Shariatpur",
        "bn.sherpur": "Sherpur",
        "bn.sirajganj": "Sirajganj",
        "bn.sunamganj": "Sunamganj",
        "bn.sylhet": "Sylhet",
        "bn.tangail": "Tangail",
        "bn.thakurgaon": "Thakurgaon",

        "bn.picture": "Picture(Passport size)*",
        "bn.identity": "Valid Identity(NID/Driving License/Passport)*",
    },
    bn: {
        "nav.home": "নীড় পাতা",
        "nav.about": "আমাদের সম্পর্কে জানুন",
        "nav.support": "আমাদের কার্যক্রমে সহযোগিতা করুন",
        "nav.partner": "অংশীদার হন",
        "nav.volunteer": "স্বেচ্ছাসেবক",
        "nav.sponsor": "আমাদের স্পনসর করুন",
        "nav.materialSupport": "বস্তুগত এবং আর্থিক সহায়তা",
        "nav.atrium": "অলিন্দ",
        "nav.photoSalon": "ছবির সেলুন",
        "nav.videoShowcase": "ভিডিও শোকেস",
        "nav.programs": "প্রকল্পসমূহ",
        "nav.contact": "যোগাযোগ",
        "vision.title": "ভিশন",
        "mission.title": "মিশন স্টেটমেন্ট",
        "MotivatingTale.title": "যারা আমাদের অনুপ্রেরণা",
        "footer.home": "নীড় পাতা",
        "footer.about": "আমাদের সম্পর্কে জানুন",
        "footer.support": "আমাদের কার্যক্রমে সহযোগিতা করুন",
        "footer.programs": "প্রকল্পসমূহ",
        "footer.contact": "যোগাযোগ",
        "project.knowMore": "আরও জানুন...",
        "engage.h2": "আমাদের সাথে যুক্ত হন",
        "engage.volunteer": "স্বেচ্ছাসেবক হোন",
        "engage.patronize": "আমাদের পৃষ্ঠপোষকতা করুন",
        "engage.thoughts": "আপনার মতামত জানান",
        "contact.officeAddress": "অফিস ঠিকানা",
        "contact.writeToUs": "আমাদের লিখুন",
        "contact.name": "নাম:",
        "contact.organization": "প্রতিষ্ঠান (ঐচ্ছিক):",
        "contact.phone": "ফোন (ঐচ্ছিক):",
        "contact.email": "ই-মেইল (প্রয়োজনীয়):",
        "contact.message": "বার্তা (সর্বাধিক ২৫০ শব্দ):",
        "contact.send": "পাঠান",

        "bn.volunteer": "বাংলাদেশী সদস্য/স্বেচ্ছাসেবক",
        "volunteer.firstName": "প্রথম নাম*",
        "volunteer.lastName": "শেষ নাম*",
        "volunteer.email": "ই-মেইল*",
        "volunteer.phone": "ফোন/মোবাইল নম্বর*",
        "volunteer.gender": "লিঙ্গ*",
        "Gender.genderSelect": "লিঙ্গ নির্বাচন করুন",
        "volunteerGender.male": "পুরুষ",
        "volunteerGender.female": "মহিলা",
        "volunteerGender.other": "অন্যান্য",

        "bn.religion": "ধর্ম (ঐচ্ছিক)",
        "religion.select": "ধর্ম নির্বাচন করুন",
        "religion.hinduism": "সনাতন",
        "religion.buddhism": "বৌদ্ধ",
        "religion.christianity": "খ্রিস্টান",
        "religion.islam": "ইসলাম",
        "religion.other": "অন্যান্য",
        "religion.no_religion": "ধর্ম নেই",

        "bn.area": "এলাকা*",
        "area.select": "এলাকা নির্বাচন করুন",
        "bn.bandarban": "বান্দরবান",
        "bn.barguna": "বরগুনা",
        "bn.barisal": "বরিশাল",
        "bn.bhola": "ভোলা",
        "bn.bogura": "বগুড়া",
        "bn.brahmanbaria": "ব্রাহ্মণবাড়িয়া",
        "bn.chandpur": "চাঁদপুর",
        "bn.chattogram": "চট্টগ্রাম",
        "bn.chuadanga": "চুয়াডাঙ্গা",
        "bn.coxsbazar": "কক্সবাজার",
        "bn.cumilla": "কুমিল্লা",
        "bn.dhaka": "ঢাকা",
        "bn.dinajpur": "দিনাজপুর",
        "bn.faridpur": "ফরিদপুর",
        "bn.feni": "ফেনী",
        "bn.gaibandha": "গাইবান্ধা",
        "bn.gazipur": "গাজীপুর",
        "bn.gopalganj": "গোপালগঞ্জ",
        "bn.habiganj": "হবিগঞ্জ",
        "bn.jamalpur": "জামালপুর",
        "bn.jashore": "যশোর",
        "bn.jhalkathi": "ঝালকাঠি",
        "bn.jhinaidah": "ঝিনাইদাহ",
        "bn.joypurhat": "জয়পুরহাট",
        "bn.khagrachari": "খাগড়াছড়ি",
        "bn.khulna": "খুলনা",
        "bn.kishoreganj": "কিশোরগঞ্জ",
        "bn.kurigram": "কুড়িগ্রাম",
        "bn.kushtia": "কুষ্টিয়া",
        "bn.lakshmipur": "লক্ষ্মীপুর",
        "bn.lalmonirhat": "লালমনিরহাট",
        "bn.madaripur": "মাদারীপুর",
        "bn.magura": "মাগুরা",
        "bn.manikganj": "মানিকগঞ্জ",
        "bn.meherpur": "মেহেরপুর",
        "bn.moulvibazar": "মৌলভীবাজার",
        "bn.munshiganj": "মুন্সিগঞ্জ",
        "bn.mymensingh": "ময়মনসিংহ",
        "bn.naogaon": "নওগাঁ",
        "bn.narail": "নড়াইল",
        "bn.narayanganj": "নারায়ণগঞ্জ",
        "bn.narsingdi": "নরসিংদী",
        "bn.natore": "নাটোর",
        "bn.netrokona": "নেত্রকোনা",
        "bn.nilphamari": "নীলফামারী",
        "bn.noakhali": "নোয়াখালী",
        "bn.pabna": "পাবনা",
        "bn.panchagarh": "পঞ্চগড়",
        "bn.patuakhali": "পটুয়াখালী",
        "bn.pirojpur": "পিরোজপুর",
        "bn.rajbari": "রাজবাড়ী",
        "bn.rajshahi": "রাজশাহী",
        "bn.rangamati": "রাঙামাটি",
        "bn.rangpur": "রংপুর",
        "bn.satkhira": "সাতক্ষীরা",
        "bn.shariatpur": "শরীয়তপুর",
        "bn.sherpur": "শেরপুর",
        "bn.sirajganj": "সিরাজগঞ্জ",
        "bn.sunamganj": "সুনামগঞ্জ",
        "bn.sylhet": "সিলেট",
        "bn.tangail": "টাঙ্গাইল",
        "bn.thakurgaon": "ঠাকুরগাঁও",

        "bn.picture": "ছবি (পাসপোর্ট সাইজ)*",
        "bn.identity": "বৈধ পরিচয় (জাতীয় পরিচয়পত্র/ড্রাইভিং লাইসেন্স/পাসপোর্ট)*"
    }
};

// Function to change the language
function changeLanguage(language) {
    localStorage.setItem('selectedLanguage', language);
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(element => {
        const translationKey = element.getAttribute('data-i18n');
        if (translations[language] && translations[language][translationKey]) {
            element.textContent = translations[language][translationKey];
        }
    });
    applyLanguage(language);
}

// Function to load the selected language from local storage
function loadLanguage() {
    const savedLanguage = localStorage.getItem('selectedLanguage') || 'en';
    changeLanguage(savedLanguage);
    document.getElementById('languageSelect').value = savedLanguage;
}

// Event listener for language selection
document.getElementById('languageSelect').addEventListener('change', function () {
    const selectedLanguage = this.value;
    changeLanguage(selectedLanguage);
});

// Load language on page load
document.addEventListener('DOMContentLoaded', loadLanguage);
